In [1]:
import sys
import os

%load_ext autoreload
%autoreload 2

sys.path.append('../')
sys.path.insert(0, os.path.dirname(os.getcwd()) + "/../")

print(sys.path)

['/home/tiendat/electric-theft-detection/../', '/home/tiendat/electric-theft-detection/notebooks', '/home/tiendat/miniconda3/envs/torchtf/lib/python39.zip', '/home/tiendat/miniconda3/envs/torchtf/lib/python3.9', '/home/tiendat/miniconda3/envs/torchtf/lib/python3.9/lib-dynload', '', '/home/tiendat/miniconda3/envs/torchtf/lib/python3.9/site-packages', '../']


In [4]:
import os
import argparse 
import math
import numpy as np
from tqdm import tqdm
from datetime import datetime

from CANdataset import CANDataset
from utils import get_prediction, cal_metric, print_results
from networks.simple_cnn import SupConCNN
from networks.classifier import LinearClassifier

from networks.resnet_big import SupConResNet
from supcon.util import set_optimizer, save_model
from supcon.util import AverageMeter
from supcon.util import adjust_learning_rate, warmup_learning_rate, accuracy
from supcon.losses import SupConLoss

#from focalloss import FocalLoss

import torch
from torch.utils.tensorboard import SummaryWriter
import torch.optim as optim
import torch.backends.cudnn as cudnn

from sklearn.metrics import f1_score

NUM_CLASSES = 2

2024-03-13 14:48:20.139403: I tensorflow/core/util/util.cc:169] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.


In [5]:
import torch

# Let's assume the following initial tensors
id_seq = torch.tensor([0, 1, 2, 3, 0, 5])
data_seq = torch.tensor([6, 7, 8, 9, 10, 11])

# Replace 0 with -1
id_seq[id_seq == 0] = -1
print(id_seq)  # Output: tensor([-1,  1,  2,  3, -1,  5])

# Reshape tensors
window_size = 2
ID_LEN = 3
DATA_LEN = 3

id_seq = id_seq.view(-1, window_size, ID_LEN)
data_seq = data_seq.view(-1, window_size, DATA_LEN)

print(id_seq)
print(data_seq)

tensor([-1,  1,  2,  3, -1,  5])
tensor([[[-1,  1,  2],
         [ 3, -1,  5]]])
tensor([[[ 6,  7,  8],
         [ 9, 10, 11]]])
